spring:
  config:
    active:
      on-profile: dev

logging:
  config: classpath:logging/log4j2-dev.xml
  level:
    root: debug

modelparam:
  a_syllable_penalty: -0.3
  noun_preference: 0.5
  longer_noun_preference: 10
  unknown_penalty: -0.1
